#!/bin/bash

if [ -z "$CLUSTER_NAME" ]; then
        echo >&2 'Error:  You need to specify CLUSTER_NAME'
        exit 1
fi

if [ -z "$DISCOVERY_SERVICE" ]; then
        echo >&2 'Error:  You need to specify DISCOVERY_SERVICE'
        exit 1
fi

/usr/bin/proxysql --initial -f -c /etc/proxysql.cnf &

sleep 10 # allow proxysql to start gracefully
echo 'Adding nodes'
exec /usr/bin/watch &

sleep 15m
echo "Starting automatic backup"
exec /usr/bin/backup &
