#!/bin/bash

get_healthy_node() {
    SERVER=`mysql --defaults-file=<(mycnf_gen) --disable-column-names -e "SELECT srv_host FROM stats.stats_mysql_connection_pool WHERE status='ONLINE';"`
    set -- $SERVER
    MYSQL_HOST=$1
}

mycnf_gen() {
    printf "[client]\nuser = %s\npassword = %s\nport = %s\nhost = %s\nconnect_timeout = 5" "${ADMIN_USER}" "${ADMIN_PASS}" "${ADMIN_PORT}" "127.0.0.1"
}

mycnfremote_gen() {
    printf "[client]\nuser = %s\npassword = %s\nport = %s\nconnect_timeout = 5" "${ADMIN_USER}" "${ADMIN_PASS}" "${ADMIN_PORT}"
}

mycnf_rootgen() {
    printf "[client]\nuser = %s\npassword = %s\nconnect_timeout = 5" "root" "${MYSQL_ROOT_PASSWORD}"
}

mysqldumpcnf_rootgen() {
    get_healthy_node
    printf "[mysqldump]\nuser = %s\npassword = %s\nhost = %s" "root" "${MYSQL_ROOT_PASSWORD}" "${MYSQL_HOST}"
}
